package com.dieunn.NewwaveInternExercise.models


import com.google.gson.annotations.SerializedName
import com.google.gson.annotations.Expose

// Auto generated by Json to Kotlin data class extension
data class APIResponse(
    @SerializedName("page")
    @Expose
    val page: Int,
    @SerializedName("results")
    @Expose
    val results: Set<Movie>,
    @SerializedName("total_pages")
    @Expose
    val totalPages: Int,
    @SerializedName("total_results")
    @Expose
    val totalResults: Int
)